spring:
  application:
    name: product-service
  boot:
    admin:
      client:
        url: http://localhost:8081
  config:
    import: http://localhost:8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 18081


