spring:
  profiles:
    active: dev
  application:
    name: product-service
  boot:
    admin:
      client:
        url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 18081
